### ISSUE TITLE
Pod status becomes Unknown after tenant'vm pod has been recreating

### ISSUE THREAD

**Issue by haoxiaoci** [kubevirt/csi-driver#110]
**What happened**:
csi-driver-controller deploy on infra cluster, and daemonset on tenant cluster side, i create a pvc, and a pod uses that pvc
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  storageClassName: kubevirt
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: busybox:1.31.1
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; sleep 1m; done"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: pv1
      mountPath: "/opt"
  volumes:
  - name: pv1
    persistentVolumeClaim:
      claimName: pvc1

```
after vm pod has been recreated on infra node, check vmi firmware ID and pretty sure that didn't change. testpod became unknown
 pod status like this:
```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               65m                default-scheduler        Successfully assigned default/test2 to hxc-manual-01-stack
  Normal   SuccessfulAttachVolume  65m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7"
  Normal   Pulled                  65m                kubelet                  Container image "busybox:1.31.1" already present on machine
  Normal   Created                 65m                kubelet                  Created container testpodwithcsi
  Normal   Started                 65m                kubelet                  Started container testpodwithcsi
  Warning  FailedMount             29m (x6 over 29m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name csi.kubevirt.io not found in the list of registered CSI drivers
  Normal   SandboxChanged          29m                kubelet                  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  29m                kubelet                  Container image "busybox:1.31.1" already present on machine
  Normal   Created                 29m                kubelet                  Created container testpodwithcsi
  Normal   Started                 29m                kubelet                  Started container testpodwithcsi
  Warning  FailedMount             60s (x7 over 91s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name csi.kubevirt.io not found in the list of registered CSI drivers
  Warning  FailedMount             27s                kubelet                  MountVolume.MountDevice failed for volume "pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7" : rpc error: code = Unknown desc = couldn't find device by serial id
```
it's shows that attachdetach-controller attach volume succeed,  but actually, tenant cluster'vm pod does not hotplug that volume. 
volumeattachment:
```
NAME                                                                   ATTACHER          PV                                         NODE                  ATTACHED   AGE
csi-68a9dd5058871b87c88923524ea68ff9fb86472005193fc0b6a6bf4bf9ff0698   csi.kubevirt.io   pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7   hxc-manual-01-stack   true       65m

```
node.status.VolumeAttached:
```
    volumesAttached:
    - devicePath: ""
      name: kubernetes.io/csi/csi.kubevirt.io^pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7
    volumesInUse:
    - kubernetes.io/csi/csi.kubevirt.io^pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7

```
i think this means ADcontroller check the attached volume, and result is volumeattachment hasn't changed.(not sure ADcontroller sync workflow, i'll check it soon.) 

kubevirt-csi-node log shows that NodeStageVolume failed.
```
I0423 09:56:35.011978       1 server.go:121] /csi.v1.Node/NodeStageVolume called with request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/csi.kubevirt.io/2cd70852e6815cdb79e4d8be455ffa4b49eb982a8ae75c94b8f08c0190136a87/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"bus":"scsi","serial":"71109ee6-8b8e-4496-a4c5-3560e32d1486","storage.kubernetes.io/csiProvisionerIdentity":"1713857400437-5590-csi.kubevirt.io"},"volume_id":"pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7"}
I0423 09:56:35.012760       1 node.go:114] Staging volume pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7
I0423 09:56:35.012777       1 node.go:397] Get the device details by serialID 71109ee6-8b8e-4496-a4c5-3560e32d1486
I0423 09:56:35.012795       1 node.go:49] lsblk -nJo SERIAL,FSTYPE,NAME
E0423 09:56:35.124168       1 node.go:122] Failed to fetch device by serialID pvc-fbac1e89-374d-41d0-b292-0e46e55ff1d7
E0423 09:56:35.124215       1 server.go:124] /csi.v1.Node/NodeStageVolume returned with error: couldn't find device by serial id
```
and it's stuck in here, until i delete the pod. 
and it got stuck on NodeUnpublishVolume() again
until i add this:
```
func IsMountPoint(mounter mount.Interface, p string) (bool, error) {
	notMnt, err := mounter.IsLikelyNotMountPoint(p)
	if err != nil {
		return false, err
	}

	return !notMnt, nil
}
func (n *NodeService) NodeUnpublishVolume(xxx) xxx
        ...
	targetPath := req.GetTargetPath()

	isMnt, err := IsMountPoint(n.mounter, targetPath)
	if err != nil {
		klog.Errorf("stat failed %v", err)
		if os.IsNotExist(err) {
			// targetPath has already been deleted
			klog.V(3).Infof("targetPath: %s has already been deleted", targetPath)
			return &csi.NodeUnpublishVolumeResponse{}, nil
		}
	}

	if !isMnt {
		if err = os.RemoveAll(targetPath); err != nil {
			klog.Errorf("failed to remove %s, %v", targetPath, err)
			return nil, fmt.Errorf("remove target path: %w", err)
		}
		return &csi.NodeUnpublishVolumeResponse{}, nil
	}
       	klog.V(5).Infof("Unmounting %s", targetPath)
	err = n.mounter.Unmount(targetPath)
        ...
```

**What you expected to happen**:
testpod should mount that pvc successfully, hope not deleting the pod to achieve this.
it's quite similar with this issue: https://github.com/kubevirt/csi-driver/issues/83 but i‘m not sure if it is the same problem.
i think in this situation the solution is volumeattachment can be deleted by csi-controller, or any other thoughts?

**How to reproduce it (as minimally and precisely as possible)**:
1. a infra cluster with kubevirt, kubevirt-csi-controller, and a tenant cluster on kubevirt vm which deployed kubevirt-csi-node.
2. create a pvc, and attach the pvc to a pod name testpod.
3. evict vm pod which allocate testpod on infra cluster.
4. after tenant cluster get up. testpod became unknown.  

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.0.0
- Kubernetes version (use `kubectl version`): v1.28.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntuy22.04
- Kernel (e.g. `uname -a`): 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64
- Install tools: rke2
- Others: N/A
